name: Production MailGuard-API

services:
  mailguard:
    build: .
    image: sharanch33/mailguard:latest
    container_name: mailguard
    env_file:
      - .env

    ports:
      - "8000:8000"
    volumes:
      - type: bind
        source: ./audit/
        target: /pmg-api/audit/


